routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Collection;
use Illuminate\Support\Str;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Builder;


use App\User;
use App\Address;
use App\Post;
use App\Tag;
use App\Mechanic;
use App\Car;
use App\Owner;
use App\Video;
use App\Comment;
use App\Demo;

use Illuminate\Support\Facades\Cookie;

// #Every time Run after you call where you want and return every time new result
// app()->bind('random',function(){
//     return Str::random();
// });

// print('I AM Bind');
// echo "<br>";
// dump(app()->make('random'));
// dump(app()->make('random'));

// #Only Once Run after you call where you want and return same result
// app()->singleton('rand',function(){
//     return Str::random();
// });

// print('I AM Singleton');
// echo "<br>";
// dump(app()->make('rand'));
// dd(app()->make('rand'));

//dd(app()->make('Hello'));

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/', ['as'=> 'firstr', 'uses'=>function () {     
//     return 'Good Luck';
// }]);

Route::get('/first', ['as'=> 'firstr', 'uses'=>function (Request $request) {
    // return 'Good Luck';
    
    // print_r(request()->all());
    // var_dump(request()->all());
    // dd(request()->all());
    return [$request->path(),
           $request->getHttpHost(),
           $request->method(),
           $request->has('first'),
           $request->url(),
           $request->is('first'),
           $request->getSchemeAndHttpHost(),
           $request->getHttpHost(),
           app_path(),
           base_path(),
           config_path(),
           database_path(),
           public_path(),
           resource_path(),
           storage_path(),
          ];
   
    #return 'Good Luck';
}]);

Route::get('/qqq', function (Request $request) {
    print_r($request->all());
    print('<br>');
    print($request->url());
    print('<br>');
    print($request->fullUrl());
    print('<br>');
    print((boolean) $request->isMethod('post'));
    print('<br>');
    dd((boolean) $request->method);
    print('<br>');
    dd ((boolean)$request->is('/'));
    if ($request->is('/')) {
        return 'WWW';
    }else{
        return 'Haii';
    }
});

Route::get('/test', ['as'=> 'testr', 'uses'=>function (Request $request) {
    #return 'Good Evening..';
    $a= [];
    $a['one'] = 'Ontru';
    $a['two'] = 'Twooo';
    $a['three'] = 'Threee';
   
    if ($request->is('admin/*')) {
        return 'WWW';
    }else{
        return 'Haii';
    }

    return response($a, 500);
    // return response()->json([
    //     'one' => 'Ontru',
    //     'two' => 'Twooo',
    //     'three' => 'Threee',
    // ]);
    #return redirect()->route('firstr');
    #return redirect(route('firstr'));
    #return redirect()->action();
    #return redirect()->away('https://laravel.com/docs/7.x/responses');
    #return 'Good Evening..';
    #return redirect('first')->with('status', 'Profile updated!');
}]);

/* 
return response('Hello World', 500)->header('Content-Type', 'application/json'); //'text/plain'

*/


Route::get('/post', function (Request $request) {

    //User::Create(['name'=>'Tig','email'=>'Tig@gmail.com','password'=>bcrypt('suresh')]);
    //  User::Create(['name'=>'boss','email'=>'boss@gmail.com','password'=>bcrypt('suresh')]);
    //  User::Create(['name'=>'don','email'=>'don@gmail.com','password'=>bcrypt('suresh')]);

    $arr = [];
    #$user = User::with('address')->get();
    $user = [];
    #$address = Address::where('country', 'India')->orWhere('id', '1')->with('account')->get();
    // $address = Address::where(function (Builder $query){
    //                 return $query->where('country', 'India')
    //                              ->orWhere('id', '1');
    //             })->get();
    // $address = Address::where('country', 'India')
    //                     ->orWhere('id', '1')->get();

    // $address = Address::where(function (Builder $query){
    //                 return $query->where('country','India')
    //                         ->where('id','1');
    //             })->account()->get();

    #$address =  Address::with('account')->get();

    // $user = User::whereHas('address', function(Builder $query){
    //     $query->where('country', 'like','%India%');
    // })->get();

    // $name = 'ram';
    // $id = '1';
    // $country = 'india';
    // $aid = '2';

    // $address = Address::where(function(Builder $qry) use($country,$aid) {
    //                 if($aid == '1') {
    //                     $qry->where('country',$country)->orWhere('id',$aid);
    //                 }else {
    //                     $qry->orWhere('id','>=','1');
    //                 }                    
    //             })
    //             ->whereHas('account', function(Builder $query) use($name, $id){
    //                 $query->where('name', $name)->orWhere('id',$id);
    //             })
    //             ->with('account')
    //             ->get();
    
    /* $user = User::whereHas('address', function(Builder $query) {
                $query->where('account_id', '1');
            },'>=',3)
            ->with('address')
            ->get(); */
   /*  $user = User::whereDoesntHave('address', function(Builder $query){
                $query->where('name','!=','ram');
                $query->where('country','India');
            })
            ->with('address')
            ->get();
            print($user); */

    // $user = User::select(['email'])->withCount(['address as address_cnt'=> function(Builder $query){
    //     $query->where('users.name','ram');
    // }])->with('address')->get();
    #print($user);

    // $first = User::where('id',2)->first();

    // $f_count = $first->loadCount('address');

    // $user = User::with(['address'=> function($query){
    //             $query->groupBy('account_id');
    //         }])->get();

    // print('<br>');
    // print($user);    
    // print('<br>');
    // print('<br>');


    // $user = User::doesntHave('address')
    //             ->with('address')
    //             ->get();
    //             print($user);

    #Address::Create(['account_id'=>$user->id, 'country'=>'India']);
    #return $address;
    #return view('user.index', [$user,$address]);
    #return view('user.index', $arr);

    $user = $address = [];

    #$user = User::select(['id','email'])->has('address')->with('address:id,country')->get();
    // $user = User::select(['id','email'])->has('address')->with(['address' => function($qry){
    //             $qry->select('id','country');
    //         }])->get();

    // $user = User::select(['id','email'])->has('address')->with(['address' => function($qry){
    //             // $qry->select('id','country');
    //             $qry->where('id','1');
    //         }])->get();

    $user = User::with('address')->select('users.id','users.email')->get();

    $address = Address::with('users')->get();

    return view('user.index', compact('user','address'));    
});


Route::get('/tag', function (Request $request) {

    $user = $address = $post = $tag = [];

    $posts = Post::first();
    #$tags = Tag::first();
    $post = Post::with('tags')->get();
    $tag = Tag::with('posts')->get();

    // $posts->tags()->attach([
    //     1=>['status'=>'Yes'],
    //     2=>['status'=>'No'],
    //     3=>['status'=>'Yes'],
    //     4=>['status'=>'No'],
    // ]);
    #$tags->posts()->attach([5]);
    #$posts->tags()->attach([6]);    
    
    return view('user.tags', compact('post','tag'));    
});


Route::get('/car', function (Request $request) {
    
    $owners = Owner::with('cars')->get();    
    $cars = Car::with(['owners','mechanics'])->get();
    $mechs = Mechanic::with('cars')->get();

    //dd($mechs);
    // Mechanic::create(['name'=>'Ravi']);
    // $car1 = Car::where('id',1)->first();
    // $car2 = Car::where('id',2)->first();
    // Owner::create(['name'=>'Mustang Owner','car_id'=> $car1->id]);
    // Owner::create(['name'=>'Ferrari Owner','car_id'=> $car2->id]);

    // $mechs = Mechanic::find(1);

    // return $mechs->carOwner;

    // $mechs = Owner::find();

    // return $mechs->carMechanic;


       
    
    return view('user.car', compact('mechs','cars','owners'));    
});


Route::get('/qqqqqqq', function (Request $request) {
    // $id =12;
    // #session(['name' => 'SURESH']);
    // $value = $request->session()->all();
    // //$value = $request->session()->all();
    // print_r('Q ---   ');
    // print_r($value); 
    // print_r('  ---  R'); exit;

    $url = url()->current();
    $url = url()->full();
    $url = url()->previous();
    return $url;
    
    // abort(404);
    // abort(403, 'Unauthorized action.');
    //$route = Route::getCurrentRoute()->getPath();
    // Log::debug('An informational message.');
    // Log::emergency('An informational emergency');
    // Log::alert('An informational alert');
    // Log::critical('An informational critical');
    // Log::error('An informational error');
    // Log::warning('An informational warning');
    // Log::notice('An informational notice');
    // Log::info('An informational info');
    // Log::debug('An informational debug');

    // Log::info('Showing user profile for user: '.$id);
    // Log::info('User failed to login.', ['id' => $id]);

    // Log::channel('slack')->info('Something happened! Apple');
    // Log::stack(['single'])->info('Something happened! QQQ');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Illuminate\Support\Facades\Storage;

use Laravel\Passport\HasApiTokens; //Passport

#use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable; ////Passport
    // use Notifiable;
    #use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','picture','str','int','country','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];   

    public static function boot()
    {
        parent::boot();
       
        static::creating(function($item){
            //dd('Creating', $item);
        });

        static::created(function($item){
            //dd('Created', $item);
        });
    }
    
    public function address()
    {
        #return $this->hasOne(Address::class, 'account_id', 'id')->withDefault(['country'=>'No COuntry']);
        return $this->hasOne(Address::class, 'account_id', 'id')->withDefault(function($abc){
            if(in_array($abc->account_id,[4,5])){
                $abc->country = 'No Country';
            }else{
                $abc->country = 'My Country';
            }            
            #$abc->country = 'No COuntry';
        });
    }

    public function addresses()
    {
        return $this->hasMany(Address::class, 'account_id', 'id');
    }

    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id', 'id');
    }

    public function getNameAttribute($value)
    {
        #return strtoupper($value);
        return ucfirst($value);
    }

    public function getCreatedAtAttribute($value)
    {
        $date=date_create($value);
        return date_format($date,"Y/m/d H:i:s a");
    }

    public function getUpdatedAtAttribute($value)
    {
        $date=date_create($value);
        return date_format($date,"Y/m/d H:i:s A");
    }

    public function getFullNameAttribute()
    {
        return "{$this->name} {$this->name}";
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucfirst($value);
    }   

    public function setPasswordAttribute($password)
    {
        return $this->attributes['password'] = bcrypt($password);
    }

    public static function uploadImage($picture, $user= null)
    {
        $file_name = $picture->getClientOriginalName();         
        if(!is_null(auth()->user()))
        {
            (new self)->deleteOldImage();
            $picture->storeAs('images',$file_name,'public');
            auth()->user()->update(['picture'=> $file_name]);  
        }elseif(!is_null($user)) {
            $picture->storeAs('images',$file_name,'public');
            $user->update(['picture'=> $file_name]);
        }       
    }
    
    public function deleteOldImage()
    {
        if(auth()->user()->picture){
            Storage::delete('/public/images/'.auth()->user()->picture);
        }
    }

}

app/Http/Controllers/API/UserController.php
<?php


namespace App\Http\Controllers\API;
use Illuminate\Http\Request; 
use App\Http\Controllers\Controller; 
use App\User; 
use Illuminate\Support\Facades\Auth; 
use Validator;

class UserController extends Controller 
{
    public $successStatus = 200;

    /** 
     * login api 
     * 
     * @return \Illuminate\Http\Response 
    */ 

    public function login()
    { 
        if(Auth::attempt(['email' => request('email'), 'password' => request('password')])){ 
            $user = Auth::user(); 
            $success['token'] =  $user->createToken('Token Name')->accessToken; 
            return response()->json(['success' => $success], $this->successStatus); 
        } 
        else{ 
            return response()->json(['error'=>'Unauthorised'], 401); 
        } 
    }

    /** 
     * Register api 
     * 
     * @return \Illuminate\Http\Response 
     */ 

    public function register(Request $request) 
    { 
        // $input = $request->all(); 

        // print_r($input); exit;

        $validator = Validator::make($request->all(), [ 
            'name' => 'required', 
            'email' => 'required|email', 
            'picture' => 'required', 
            'password' => 'required', 
            'c_password' => 'required|same:password', 
        ]);
        if ($validator->fails()) { 
            return response()->json(['error'=>$validator->errors()], 401);            
        }
        $input = $request->all(); 
        unset($input['picture']);       
        //$input['password'] = bcrypt($input['password']);        
        $user = User::create($input);
        if($user)
        {
            User::uploadImage($request->picture, $user);
            $success['token'] =  $user->createToken('Token Name')->accessToken; 
            $success['name'] =  $user->name;
            $success['msg'] = 'User registered successfully.'; 
        }else {
            $success['msg'] = 'Something went wrong'; 
            $this->successStatus = 400;
        }       
        return response()->json(['success'=>$success], $this->successStatus); 
    }

    /** 
     * details api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function details() 
    { 
        $user = Auth::user(); 
        return response()->json(['success' => $user], $this->successStatus); 
    } 
}

resources/views/user/car.blade.php
@extends('main')

@section('title', 'Tags')

@section('sidebar')    
    <h1> We are from Serviceprovider boot function </h1>
    <h3>{{$iam}} </h3>
    <h3>{{$anotherone}} </h3>
@endsection

@section('content')
    <h1>OWNERS</h1>
    @foreach($owners as $own)
    <tr>
       <td>
        <h2>{{$own->name}}</h2>
        <p>Car - {{$own->cars->model}}</p>
        <p>Mechanic - {{optional($own->carMechanic)->name}}</p>
       </td>
    </tr>
    @endforeach 
    <hr><br/>

    <h1>CARS</h1>
    @foreach($cars as $car)
    <tr>
       <td>
        <h2>{{$car->model}}</h2>
        <p>Owner - {{$car->owners->name}}</p>
        <p>Mechanic - {{$car->mechanics->name}}</p>
       </td>
    </tr>
    @endforeach 
    <hr><br/>

    <h1>MECHANICS</h1>
    @foreach($mechs as $mec)
    <tr>
       <td>
            <h2>{{$mec->name}}</h2>   
            <p>Car - {{$mec->cars->model}}</p>
            <p>Owner - {{$mec->carOwner->name}}</p>
       </td>
    </tr>
    @endforeach
    <hr><br/>
    
@endsection

resources/views/user/image_upload.blade.php
@extends('main')

@section('title', 'Image Upload')

@section('content')
    <h3>Image Upload...</h3>
    @auth
      <img src="{{asset('storage/images/'.Auth::user()->picture)}}" width="200" height="200"/>
    @else
      <p>No Image Found..</p>
    @endauth

    <x-img-alert>
       <p>Hai I am alert...</p>
    </x-img-alert>

    @if($errors->any())
    {{print_r($errors->all())}}
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $k=>$v)
                   <li>{{$k}} - {{$v}}</li>
                @endforeach
            </ul>
        </div>
    @endif
   
    <h3>AAAAAA</h3>

    @error('picture')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <form name="image_upload" method="post" action="{{route('upload')}}" enctype="multipart/form-data">
        @csrf
        Select image to upload:
        <input type="file" name="picture" id="picture">
        <input type="submit" value="Upload Image">
    </form>

@endsection

resources/views/user/index.blade.php
@extends('main')

@section('title', 'Page Title')

@section('sidebar')
    @parent

    <p>This is appended to the master sidebar.</p>
@endsection

@section('content')

    <pre>
        {{$user}}
        <hr><br>
        {{$address}}
    </pre>

    <p>TABLE 1</p>
    <table>
    @foreach($user as $a)
    <tr>
       <td>{{$a->email}} 
       [
          {{$a->address->country}} 
       ]
       ({{$a->address_cnt}})</td>
    </tr>
    @endforeach
    </table>

    <br><hr>
    <p>TABLE 2</p>
    <table>
    @foreach($address as $b)
    <tr>
       <td>{{$b->country}} 
       [
        {{$b->users->email}}     
       ]
       </td>
    </tr>
    @endforeach
    </table>

@endsection

resources/views/user/others.blade.php
@extends('main')

@section('title', 'Tags')

@section('sidebar')
    @parent   
@endsection

@section('content')
    <h1>OWNERS</h1>
    
    <hr><br/>

    <h1>CARS</h1>
   
    <hr><br/>

    <h1>MECHANICS</h1>
    
    <hr><br/>
    
@endsection

resources/views/user/tags.blade.php
@extends('main')

@section('title', 'Tags')

@section('sidebar')
    @parent   
@endsection

@section('content')
    @foreach($post as $ps)
    <tr>
       <td>
       <h2>{{$ps->title}} ({{$ps->user->name}})</h2>
            <ul>
                @foreach($ps->tags as $tags)
                   <li>{{$tags->name}}  -  {{$tags->posttag->created_at}} Status - {{$tags->posttag->status}}</li> 
                @endforeach
           </ul>
       </td>
    </tr>
    @endforeach 
    <hr><br/>
    @foreach($tag as $tg)
    <tr>
       <td>
       <h2>{{$tg->name}}</h2> 
            <ul>
                @foreach($tg->posts as $post)
                   <li>{{$post->title}}  -  {{$post->pivot->created_at}}</li> 
                @endforeach
           </ul>
       </td>
    </tr>
    @endforeach   
@endsection

resources/views/user/test.blade.php
@extends('main')
@section('title', 'Test Page')

@section('content')
    <h1>OWNERS</h1>
    
    <hr><br/>

    <h1>CARS</h1>
   
    <hr><br/>

    <h1>MECHANICS</h1>
    
    <hr><br/>
    
@endsection